FROM node:16 as build

WORKDIR /usr/app/build/

COPY build/package*.json ./

RUN npm install --only=prod

COPY build/ ./

RUN npm run build

FROM nginx

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]