version: "3"
services:
  client:
    container_name: notification-client-dev
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    networks:
      - notification-system
  server:
    container_name: notification-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${EXPOSED_PORT}:${PORT}"
    env_file: ./server/.env
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
      - "/usr/src/app/files:${FILES_DIR}"
    networks:
      - notification-system
networks:
  notification-system:
    driver: bridge
volumes:
  mongo-data:
    driver: local